name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 0 * * *' # every day at midnight

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            platform: linux/amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Docker meta base
        id: meta-base
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/base

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build base
        id: build-base
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:images/base"
          file: "base.Dockerfile"
          labels: ${{ steps.meta-base.outputs.labels }}
          tags: ghcr.io/${{ github.repository }}/base
          outputs: type=image,push-by-digest=true,name-cannonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests/base
          digest="${{ steps.build-base.outputs.digest }}"
          touch "${{ runner.temp }}/digests/base/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: base-digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/base/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests/base
          pattern: base-digests-*
          merge-multiple: true
      
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/base
          tags: |
            latest
            ${{ github.sha }}
            ${{ github.ref_name }}
      
      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests/base
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ github.repository }}/base@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ github.repository }}/base:${{ steps.meta.outputs.version }}
          
