name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 0 * * *' # every day at midnight

  workflow_dispatch:

jobs:
  images-amd64:
    runs-on: ubuntu-latest
    name: images-amd64
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push base
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:images/base"
          push: true
          file: "base.Dockerfile"
          tags: ghcr.io/${{github.repository}}/base:latest
      
      - name: Build and push seng201
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:images/seng201"
          push: true
          file: "seng201.Dockerfile"
          tags: ghcr.io/${{github.repository}}/seng201:latest

  images-arm64:
    runs-on: ubuntu-24.04-arm
    name: images-arm64
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push base
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:images/base"
          push: true
          file: "base.Dockerfile"
          tags: ghcr.io/${{github.repository}}/base:latest
      
      - name: Build and push seng201
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:images/seng201"
          push: true
          file: "seng201.Dockerfile"
          tags: ghcr.io/${{github.repository}}/seng201:latest
