name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 0 * * *' # every day at midnight

  workflow_dispatch:

jobs:
  build-base:
    uses: ./.github/workflows/build-and-merge.yaml
    with:
      image: base
    secrets: inherit
  
  build-seng201:
    needs: build-base
    uses: ./.github/workflows/build-and-merge.yaml
    with:
      image: seng201
    secrets: inherit
  
  build-cosc261:
    needs: build-base
    uses: ./.github/workflows/build-and-merge.yaml
    with:
      image: cosc261
    secrets: inherit