on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            platform: linux/amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
    steps:
      - name: Prepare
        shell: bash
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ inputs.image }}
        
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.runner }}:images/${{ inputs.image }}
          file: "${{ inputs.image }}.Dockerfile"
          labels: ${{ steps.meta.outputs.labels }}
          tags: ghcr.io/${{ github.repository }}/${{ inputs.image }}
          outputs: type=image,push-by-digest=true,push=true,name-cannonical=true
        
      - name: Export digest
        shell: bash
        run: |
          mkdir -p ${{ runner.temp }}/digests/${{ inputs.image }}
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${{ inputs.image }}/${digest#sha256:}"
        
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.image }}-digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/${{ inputs.image }}/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests/${{ inputs.image }}
          pattern: ${{ inputs.image }}-digests-*
          merge-multiple: true
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          image: ghcr.io/${{ github.repository }}/${{ inputs.image }}
          tags:
            latest
            ${{ github.sha }}
            ${{ github.ref_name }}
      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests/${{ inputs.image }}
        shell: bash
        run: |
            docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
              $(printf 'ghcr.io/${{ github.repository }}/${{ inputs.image }}@sha256:%s ' *)
